apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: hello-gke-cicd
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: gcr.io/rugged-precept-258803/jenkinscd-helloworld-gke:12
        ports:
        - containerPort: 8080
        env: 
          - name: PORT
            value: "8080"
        
