apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: jenkins-cd-helloworld-gke
  namespace: helloworld-api
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: gcr.io/rugged-precept-258803/jenkinscd-helloworld-gke:latest
        ports:
        - containerPort: 8080
        env: 
          - name: PORT
            value: "8080"
        
